# Generated by Django 6.0.4 on 2026-04-12 03:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_location_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_domain', models.CharField(max_length=255, unique=True)),
                ('access_token', models.CharField(max_length=512)),
                ('plan', models.CharField(default='starter', max_length=20)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('uninstalled_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('store_name', models.CharField(blank=True, max_length=255)),
                ('store_email', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('shopify_charge_id', models.CharField(blank=True, max_length=100)),
                ('billing_status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('frozen', 'Frozen'), ('cancelled', 'Cancelled')], default='trial', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('last_product_sync', models.DateTimeField(blank=True, null=True)),
                ('last_order_sync', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-installed_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ordered', 'Ordered'), ('partial', 'Partially Received'), ('received', 'Received'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payment_terms', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('sent_to_supplier_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='core.location')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='core.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('received_qty', models.PositiveIntegerField(default=0)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='core.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_by', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('synced_to_shopify', models.BooleanField(default=False)),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivings', to='core.polineitem')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.shop'),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payment_terms', models.CharField(choices=[('prepaid', 'Prepaid'), ('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_60', 'Net 60'), ('on_receipt', 'On Receipt'), ('other', 'Other')], default='net_30', max_length=50)),
                ('lead_time_days', models.PositiveIntegerField(default=7)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='core.shop')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('shop', 'name')},
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='core.supplier'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_product_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('product_type', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='active', max_length=20)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.shop')),
                ('default_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.supplier')),
            ],
            options={
                'unique_together': {('shop', 'shopify_product_id')},
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_variant_id', models.CharField(max_length=50)),
                ('shopify_inventory_item_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('sku', models.CharField(blank=True, max_length=255)),
                ('barcode', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_point', models.PositiveIntegerField(default=0)),
                ('reorder_qty', models.PositiveIntegerField(default=0)),
                ('supplier_sku', models.CharField(blank=True, max_length=255)),
                ('supplier_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.shop')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='core.supplier')),
            ],
            options={
                'unique_together': {('shop', 'shopify_variant_id')},
            },
        ),
        migrations.AddField(
            model_name='polineitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_line_items', to='core.variant'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('shop', 'shopify_location_id')},
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorder',
            unique_together={('shop', 'po_number')},
        ),
        migrations.CreateModel(
            name='SalesVelocity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_daily_sales_7d', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('avg_daily_sales_30d', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('avg_daily_sales_90d', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('total_sold_30d', models.PositiveIntegerField(default=0)),
                ('total_sold_90d', models.PositiveIntegerField(default=0)),
                ('days_of_stock', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('abc_class', models.CharField(choices=[('A', 'A - Top 80%'), ('B', 'B - Next 15%'), ('C', 'C - Bottom 5%')], default='C', max_length=1)),
                ('is_dead_stock', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_velocity', to='core.location')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_velocity', to='core.variant')),
            ],
            options={
                'unique_together': {('variant', 'location')},
            },
        ),
        migrations.CreateModel(
            name='InventoryLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.IntegerField(default=0)),
                ('on_hand', models.IntegerField(default=0)),
                ('incoming', models.IntegerField(default=0)),
                ('committed', models.IntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_levels', to='core.location')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_levels', to='core.variant')),
            ],
            options={
                'unique_together': {('variant', 'location')},
            },
        ),
    ]
