# Generated by Django 6.0.4 on 2026-04-12 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocktake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('total_counted', models.PositiveIntegerField(default=0)),
                ('total_variance', models.IntegerField(default=0)),
                ('variance_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocktakes', to='core.location')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocktakes', to='core.shop')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StocktakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_qty', models.IntegerField(default=0)),
                ('counted_qty', models.IntegerField(blank=True, null=True)),
                ('stocktake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.stocktake')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocktake_items', to='core.variant')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_transit', 'In Transit'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='core.location')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='core.shop')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='core.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('received_qty', models.PositiveIntegerField(default=0)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.transfer')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.variant')),
            ],
        ),
    ]
